### ISSUE TITLE
Multiblock error when restoring a course

### ISSUE THREAD

**Issue by israelpelayo** [catalyst/moodle-block_multiblock#64] opened 2020-08-01 00:45 UTC
This error happened when, from a backup of my course, I tried to do its restore within a new course. The error was cleared when I disabled the blocks. I guess the error comes from Multiblock, because it had not previously happened to me until I inserted the blocks inside Multiblock.

I hope to be able to collaborate with the development of this excellent complement.

![Multiblock error](https://user-images.githubusercontent.com/69062468/89089978-a1ec5880-d365-11ea-8da6-366eeb730f82.jpg)

**Comment by Arantor** [comment] 2020-08-02 19:59
Interesting bug report, I haven't seen that since the earliest attempts to work on backup/restore.

What version of Moodle is this, what blocks are inside the multiblock? If you are able, I'd appreciate seeing the backup itself (but I appreciate this might not be achievable). Alternatively if you can make a small course that has no actual content (or user data) that still has the same symptoms, I'd definitely like to see it.

**Comment by sanchez-martin-jose** [comment] 2022-08-22 09:44
Moodle 4.0.1+ (Build: 20220701)
Multiblock 1.3.2 2020060102

Same here, I have defined a custom region bloques-inferior

This is a backup of a test course with the multiblock in the custom region

https://drive.google.com/file/d/166ik9mE8YcCTwiGH_FK0GsXkKy7ZNF15/view?usp=sharing

**Comment by danmarsden** [comment] 2022-09-06 21:34
I've been looking at this recently and I've been able to reproduce this when using the Import (merge contents) process (no other restore processes seem to be affected) - it gets triggered when the restore plan tries to restore the blocks that sit inside the multiblock. I'm guessing (at this stage) that the multiblock gets skipped from being restored as it's detected as a duplicate somewhere and then when trying to restore the blocks that sit inside the multiblock it can't because the multi-block itself was skipped.

**Comment by danmarsden** [comment] 2022-09-07 00:06
I can't find a way to fix this easily in the multi-block code, but have proposed a fix for this in the core restore blocks handling here:
https://tracker.moodle.org/browse/MDL-75668

**Comment by danmarsden** [comment] 2022-09-29 01:33
A fix for this landed in supported moodle versions this week so closing it here now.

**Closed as completed by danmarsden** 2022-09-29 01:33 UTC
